### ISSUE TITLE
PNG download is broken

### ISSUE THREAD

**Issue by jmunowitch** [ceresimaging/image-tiler#40]
Here is what is failing:
https://app.ceresimaging.net/imagery/2ab0116d-9d60-4182-9317-4e987d216f48.png

I assume this is the tile-server url for it, since it is making the same error 
https://tiles.ceresimaging.net/imagery/2ab0116d-9d60-4182-9317-4e987d216f48.png

Here is the error on both:
>Cannot read property ‘map’ of undefined

**Comment by maurimiranda** [comment]
Fixed!
