### ISSUE TITLE
Download GeoTiff manually before calling Mapnik

### ISSUE THREAD

**Issue by maurimiranda** [ceresimaging/image-tiler#5]
Each image must be downloaded only once, the first time a request needs it. If any other request asks for the same image, it should put on-hold until the image is ready.

Destination folder must be configurable through environment variables and it will be shared between all instances of ECS.

Image files should be stored only for a certain time and must be deleted periodically. I would use a daily basis cleaning task.

**Comment by tweitemier** [comment]
I don't have permission to close this but I think it can be! Nice job on speeding up the loading, it's like night and day! Multiple seconds difference
