### ISSUE TITLE
Move Data Import process from tiler

### ISSUE THREAD

**Issue by jmunowitch** [ceresimaging/image-tiler#8]
Gssurgo data (US Soil Data) is available to download here:

> Data from: https://nrcs.app.box.com/v/soils/
> From: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/soils/survey/geo/?cid=nrcs142p2_053627
> The information was collected at scales ranging from 1:12,000 to 1:63,360. More details were gathered at a scale of 1:12,000 than at a scale of 1:63,360

A script to automatically download and process this data would be useful to update the data in the future.

This will also lead to scripts to import soil data for other regions, such as Australia

**Comment by jmunowitch** [comment]
This all may reside in https://github.com/ceresimaging/tiler

**Comment by maurimiranda** [comment]
This file contains the scripts to import gssurgo data: [import-data.zip](https://github.com/ceresimaging/image-tiler/files/3842878/import-.zip)
